spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: 123
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 1
      minimum-idle: 1
      leakDetectionThreshold: 60000
      keepaliveTime: 30000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
server:
  tomcat:
    connection-timeout: 5000
    max-threads: 1
    min-spare-threads: 1